#!/usr/bin/env ruby

# Copyright (c) 2021-2022 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

require 'optparse'

if ARGV.size == 0
    puts "No SID specified!"
    puts
    exit 0
end

SID = ARGV.shift

base64_urlsafe = [
'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P',
'Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f',
'g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v',
'w','x','y','z','0','1','2','3','4','5','6','7','8','9','-','_']

buf = ""
save = false
i = 60
j = 0
n = 0
while i >= 0 do
    n = (SID.to_i >> i) & 0x3f
#puts "i #{i} n #{n}  save #{save}"
    if (n != 0)
        save = true # Start saving after first non zero data
    end
    if (save)
        buf = buf + base64_urlsafe[n]
    end

    i -= 6
end
puts buf
