#!/usr/bin/env ruby

# Copyright (c) 2021-2022 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

require 'optparse'

if ARGV.size == 0
    puts "No SID specified!"
    puts
    exit 0
end

SID = ARGV.shift

res = 0

SID.each_char do |c|
    if c == '-'
        s = 62
    elsif c == '_'
        s = 63
    elsif /[A-Z]/.match(c)
        s = c.ord - 'A'.ord
    elsif /[a-z]/.match(c)
        s = c.ord - 'a'.ord + 26
    elsif /[0-9]/.match(c)
        s = c.ord - '0'.ord + 52
    else
        puts "Invalid SID!"
        exit 1
    end
    res <<= 6
    res += s
end
puts res

exit 0
